secrets:
  deps_file:
    secretName: deps-file
  api_key:
    secretName: api-key
  file_database:
    secretName: file-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  redis_password:
    secretName: redis-password
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

file:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-file"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

file_consumer:
  replicaCount: 1
  image:
    path: '/deps-dev-x01/deps-file'
    pullPolicy: IfNotPresent
    tag: ''
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

file_settings:
    ENV: dev

    DATABASE_PORT: '5432'
    DATABASE_DRIVER: psycopg2
    DATABASE_DIALECT: postgresql
    DATABASE_REQUIRE_SECURE_TRANSPORT: false
    DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
    DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
    DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

    AUTH_VERIFY_SSL: false

    GROUP_URL: "http://groups:8000"
    FILE_STORAGE_URL: 'http://file-storage-nginx:8000'
    DOCUMENT_URL: "http://backend:8000"
    FILES_BATCH_URL: "http://files-batch:8000"

    OBJECT_STORAGE_MODE: "sync"
    OBJECT_STORAGE_TYPE: "file-storage"

    LOG_LEVEL: "INFO"
    DOCUMENTATION_ENABLED: "true"

    RABBITMQ_TLS_ENABLED: false

    KAFKA_GROUP_ID: file
    KAFKA_AUTO_OFFSET_RESET: earliest
    KAFKA_SECURITY_ENABLED: false

    # Azure Service Bus
    ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'

    # Telemetry
    INSTRUMENTATION_ENABLED: false
    SERVICE_NAME: file
    EXPORTER_TYPE: azure

    # Object storage
    # aws
    S3_BUCKET_NAME: bucket_name
    S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com
    # gcp
    GCP_BLOB_STORAGE_BUCKET_NAME: "bucket_name"

helm:
  helm_logs_job_enabled: false

message_broker_asb_without_manage_permission:
  enabled: false

csi:
  csi_default_name: deps-file
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

file_vault_enabled:
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: deps-file
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: keycloak-certs-endpoint
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: message-broker-connection-string
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: database-host
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: database-db
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: password
    - name: AZURE_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-secret-access-key
    - name: S3_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-storage-s3-endpoint-url
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-storage-s3-bucket-name
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: gcp-api-key


file_vault_disabled:
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: deps-file
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: keycloak-certs-endpoint
          key: keycloak-certs-endpoint
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-connection-string
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: database-host
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: file-database
          key: database-db
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: file-database
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: file-database
          key: password
    - name: AZURE_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-secret-access-key
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: gcp-credentials
          key: gcp-api-key


file_consumer_vault_enabled:
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: deps-file
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: keycloak-certs-endpoint
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: message-broker-connection-string
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: database-host
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: database-db
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: password
    - name: AZURE_CONNECTION_STRING
      valueFrom:
          secretKeyRef:
            name: deps-file
            key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-secret-access-key
    - name: S3_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-storage-s3-endpoint-url
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: aws-storage-s3-bucket-name
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: deps-file
          key: gcp-api-key


file_consumer_vault_disabled:
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: deps-file
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: keycloak-certs-endpoint
          key: keycloak-certs-endpoint
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-connection-string
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: database-host
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: file-database
          key: database-db
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: file-database
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: file-database
          key: password
    - name: AZURE_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-secret-access-key
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: gcp-credentials
          key: gcp-api-key
