apiVersion: v1
kind: ConfigMap
metadata:
  name: file-configmap
  labels:
    {{- include "deps-file.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.file_settings.ENV }}
  DATABASE_PORT: '{{ .Values.file_settings.DATABASE_PORT }}'
  DATABASE_DIALECT: '{{ .Values.file_settings.DATABASE_DIALECT }}'
  DATABASE_DRIVER: '{{ .Values.file_settings.DATABASE_DRIVER }}'
  DATABASE_REQUIRE_SECURE_TRANSPORT: '{{ .Values.file_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}'

  {{- if .Values.file_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
  DATABASE_SSLKEY: {{ .Values.migration_settings.DATABASE_SSLKEY_PATH }}
  DATABASE_SSLCERT: {{ .Values.migration_settings.DATABASE_SSLCERT_PATH }}
  DATABASE_SSLROOTCERT: {{ .Values.migration_settings.DATABASE_SSLROOTCERT_PATH }}
  {{- end }}

  GROUP_URL: '{{ .Values.file_settings.GROUP_URL }}'
  FILE_STORAGE_URL: '{{ .Values.file_settings.FILE_STORAGE_URL }}'
  DOCUMENT_URL: '{{ .Values.file_settings.DOCUMENT_URL }}'
  FILES_BATCH_URL: '{{ .Values.file_settings.FILES_BATCH_URL }}'

  OBJECT_STORAGE_MODE: '{{ .Values.file_settings.OBJECT_STORAGE_MODE }}'
  OBJECT_STORAGE_TYPE: '{{ .Values.file_settings.OBJECT_STORAGE_TYPE }}'

  AUTH_VERIFY_SSL: '{{ .Values.file_settings.AUTH_VERIFY_SSL }}'

  LOG_LEVEL: '{{ .Values.file_settings.LOG_LEVEL }}'
  DOCUMENTATION_ENABLED: '{{ .Values.file_settings.DOCUMENTATION_ENABLED }}'

  KAFKA_GROUP_ID: '{{ .Values.file_settings.KAFKA_GROUP_ID }}'
  KAFKA_AUTO_OFFSET_RESET: '{{ .Values.file_settings.KAFKA_AUTO_OFFSET_RESET }}'

  {{ if .Values.file_settings.RABBITMQ_TLS_ENABLED }}
  RABBITMQ_TLS_HOST: '{{ .Values.file_settings.RABBITMQ_TLS_HOST }}'
  RABBITMQ_TLS_PORT: '{{ .Values.file_settings.RABBITMQ_TLS_PORT }}'
  RABBITMQ_TLS_USER: '{{ .Values.file_settings.RABBITMQ_TLS_USER }}'
  RABBITMQ_TLS_VHOST: '{{ .Values.file_settings.RABBITMQ_TLS_VHOST }}'
  RABBITMQ_TLS_SUBJECT: '{{ .Values.file_settings.RABBITMQ_TLS_SUBJECT }}'
  RABBITMQ_TLS_CA_CERT: '{{ .Values.file_settings.RABBITMQ_TLS_CA_CERT }}'
  RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.file_settings.RABBITMQ_TLS_CLIENT_CERT }}'
  RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.file_settings.RABBITMQ_TLS_CLIENT_KEY }}'
  {{ end }}

  {{ if .Values.file_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.file_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.file_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}
  {{ if .Values.message_broker_asb_without_manage_permission.enabled }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.file_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  # Telemetry
  INSTRUMENTATION_ENABLED: '{{ .Values.file_settings.INSTRUMENTATION_ENABLED }}'
  SERVICE_NAME: '{{ .Values.file_settings.SERVICE_NAME }}'
  EXPORTER_TYPE: '{{ .Values.file_settings.EXPORTER_TYPE }}'

  # Object storage
  # aws
  S3_BUCKET_NAME: '{{ .Values.file_settings.S3_BUCKET_NAME }}'
  S3_ENDPOINT_URL: '{{ .Values.file_settings.S3_ENDPOINT_URL }}'
  # gcp
  GCP_BLOB_STORAGE_BUCKET_NAME: '{{ .Values.file_settings.GCP_BLOB_STORAGE_BUCKET_NAME }}'
